services:
  - type: web
    name: instagram-backend
    runtime: java
    rootDir: backend
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/Instagram-0.0.1-SNAPSHOT.jar
    autoDeploy: true
