spring.datasource.url=jdbc:postgresql://localhost:5432/instagram-db
spring.datasource.username=postgres
spring.datasource.password=Password@2026
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=2000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
spring.jackson.time-zone=Asia/Kolkata

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=200MB

cloudinary.cloud_name=yyxwi7pf
cloudinary.api_key=915116991772473
cloudinary.api_secret=PcD_DhtyIFPCY0sYDOEgVG_CNuI

jwt.secret=mySecretkeyinstagramhfjnj2643983dcbbxnjxshvdfrfrf

server.port= 8080

server.compression.enabled=true
server.compression.mime-types=application/json,application/javascript,text/html,text/css
server.compression.min-response-size=1024




#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.hikari.maximum-pool-size=20
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=300000
#spring.datasource.hikari.connection-timeout=2000
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.batch_size=50
#spring.jpa.properties.hibernate.order_inserts=true
#spring.jpa.properties.hibernate.order_updates=true
#spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
#spring.jackson.time-zone=Asia/Kolkata
#
#spring.servlet.multipart.max-file-size=20MB
#spring.servlet.multipart.max-request-size=200MB
#
#cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
#cloudinary.api_key=${CLOUDINARY_API_KEY}
#cloudinary.api_secret=${CLOUDINARY_API_SECRET}
#
#jwt.secret=${JWT_SECRET}
#
#server.port=${SERVER_PORT:8080}
#
#server.compression.enabled=true
#server.compression.mime-types=application/json,application/javascript,text/html,text/css
#server.compression.min-response-size=1024

# Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Kafka configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=instagram-feed-group
spring.kafka.consumer.auto-offset-reset=earliest

# App Custom configs
app.kafka.topic.post-activity=post-activity-events
app.feed.flush-interval-ms=3000
app.feed.recalculate-interval-ms=6000
app.feed.popularity.like-weight=3
app.feed.popularity.comment-weight=5
app.feed.popularity.share-weight=7
app.feed.popularity.decay-rate=0.05
app.feed.popularity.redis-limit=500
app.redis.key.popular-posts=popular_posts
